apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autoheater

commonLabels:
  app.kubernetes.io/name: autoheater

replicas:
  - name: autoheater
    count: 1

images:
  - name: ghcr.io/achetronic/autoheater:latest
    newTag: v0.1.2

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
